name: 'Dagger for GitHub'
description: 'GitHub Action for Dagger, a programmable deployment system'
author: 'dagger'
branding:
  color: 'green'
  icon: 'package'

inputs:
  version:
    description: 'Dagger CUE version'
    default: '0.2.232'
    required: false
  args:
    description: 'Arguments to pass to Dagger'
    required: false
    deprecationMessage: 'Use cmds input instead'
  cmds:
    description: 'List of Dagger commands'
    required: false
  workdir:
    description: 'Working directory (below repository root)'
    default: '.'
    required: false
  install-only:
    description: 'Just install Dagger'
    default: 'false'
    required: false
  cleanup:
    description: 'Cleanup Dagger home folder at the end of a job'
    default: 'true'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/index.js'
