name: ci

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches:
      - 'main'
      - 'releases/v*'
    tags:
      - 'v*'
  pull_request:

jobs:
  version:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - latest
          - 0.1.0-alpha.31
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Init env
        run: |
          mkdir -p ~/.config/dagger
          cp ./test/keys.txt ~/.config/dagger/
      -
        name: Dagger
        uses: ./
        with:
          version: ${{ matrix.version }}
          args: up --no-cache
          workdir: ./test

  age-secret:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Dagger
        uses: ./
        with:
          age-key: ${{ secrets.DAGGER_AGE_KEY_TEST }}
          args: up --no-cache
          workdir: ./test

  install-only:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - latest
          - 0.1.0-alpha.17
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Init env
        run: |
          mkdir ~/.config/dagger
          cp ./test/keys.txt ~/.config/dagger/
      -
        name: Dagger
        uses: ./
        with:
          version: ${{ matrix.version }}
          install-only: true
      -
        name: Check
        run: |
          dagger version
