name: test

on:
  push:
    branches:
      - 'main'
      - 'releases/v*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Validate
        uses: docker/bake-action@v3
        with:
          targets: validate
      -
        name: Test
        uses: docker/bake-action@v3
        with:
          targets: test
      -
        name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/clover.xml
